version: "3"

services:
  web:
    image: node:21.7.3-alpine3.19
    container_name: project-node
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/var/www/project
    working_dir: /var/www/project
    command: >
      sh -c "npm install
      && npm run dev -- --host 0.0.0.0"
    env_file:
      - .env
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/media:/vol/web/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
